// SPDX-License-Identifier: MIT
pragma solidity ^0.8.21;

/**
 * @title IUltraVerifier
 * @notice Interface for Noir UltraHonk proof verifier (bb 0.84.0)
 * @dev Compatible with Barretenberg 0.84.0 HonkVerifier contracts
 *      Generated by: bb write_solidity_verifier (UltraHonk)
 */
interface IUltraVerifier {
    /**
     * @notice Verify a zero-knowledge proof
     * @param _proof The proof bytes generated by Noir prover (UltraHonk)
     * @param _publicInputs Array of public inputs to the circuit
     * @return bool True if the proof is valid, false otherwise
     */
    function verify(bytes calldata _proof, bytes32[] calldata _publicInputs) external view returns (bool);
}
